import {initializeApp} from "https://www.gstatic.com/firebasejs/12.0.0/firebase-app.js";
import {getAuth,GoogleAuthProvider,signInWithPopup,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js";
import {getFirestore,doc,getDoc,setDoc,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyCIMT-DdodNdetlKApnrbpRdWMkMRlBKe4",authDomain:"college-pickem-6caa9.firebaseapp.com",projectId:"college-pickem-6caa9",storageBucket:"college-pickem-6caa9.firebasestorage.app",messagingSenderId:"706617130616",appId:"1:706617130616:web:48d7ae2faf9b1c796ab78d",measurementId:"G-9ZYCQ6806Y"};
const fb=initializeApp(firebaseConfig),auth=getAuth(fb),db=getFirestore(fb),google=new GoogleAuthProvider();
const games=[["#13 Alabama", "East Carolina", -28.5, 2], ["#7 Miami", "Stanford", -24.5, 2], ["#14 USC", "Fresno State", -22.5, 2], ["#6 Indiana", "North Texas", -40.5, 2], ["#23 Houston", "Oregon State", -20.5, 2], ["Auburn", "Baylor", -6.5, 1], ["#2 Oregon", "Boise State", -24.5, 2], ["#18 Penn State", "Marshall", -24.5, 2], ["Cincinnati", "Boston College", -7.5, 1], ["Arkansas", "North Alabama", -40.5, 1], ["Mississippi State", "UL Monroe", -28.5, 1], ["#11 LSU", "Clemson", -10.5, 2], ["#16 Michigan", "Western Michigan", -27.5, 2], ["Florida", "Florida Atlantic", -27.5, 1], ["UCLA", "California", -1.5, 1], ["#17 Washington", "Washington State", -23.5, 2], ["#4 Notre Dame", "Wisconsin", -20.5, 2], ["#9 Ole Miss", "#24 Louisville", -6.5, 3], ["#19 SMU", "Florida State", -2.5, 2], ["Georgia Tech", "Colorado", -6.5, 1]].map((g,i)=>({id:"g"+(i+1),fav:g[0],dog:g[1],spread:g[2],points:g[3]}));let user=null,profile=null,picks={};const $=x=>document.getElementById(x);
function renderGames(){$("games").innerHTML=games.map(g=>`<div class="game"><div class="game-head"><b>${g.fav} ${g.spread}</b><span class="points">${g.points} pt${g.points>1?"s":""}</span></div><div class="choices"><button class="choice ${picks[g.id]===g.fav?"selected":""}" data-g="${g.id}" data-p="${g.fav}">${g.fav} ${g.spread}</button><button class="choice ${picks[g.id]===g.dog?"selected":""}" data-g="${g.id}" data-p="${g.dog}">${g.dog} +${Math.abs(g.spread)}</button></div></div>`).join("");document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{picks[b.dataset.g]=b.dataset.p;renderGames()})}
function renderMy(){$("myPicksView").innerHTML=games.map(g=>`<p><b>${g.id.toUpperCase()}</b>: ${picks[g.id]||"No pick yet"}</p>`).join("")}
async function loadPicks(){let s=await getDoc(doc(db,"weeks","week-1","entries",user.uid));if(s.exists()){let d=s.data();picks=d.picks||{};$("clemsonScore").value=d.tiebreak?.clemson??"";$("lsuScore").value=d.tiebreak?.lsu??""}renderGames();renderMy()}
async function loadProfile(){let s=await getDoc(doc(db,"users",user.uid));profile=s.exists()?s.data():null;if(!profile){$("profileCard").hidden=false;$("appArea").hidden=true;return}$("profileCard").hidden=true;$("appArea").hidden=false;$("adminTab").hidden=profile.role!=="admin";await loadPicks()}
$("googleBtn").onclick=()=>signInWithPopup(auth,google).catch(e=>$("authMsg").textContent=e.message);$("emailCreate").onclick=()=>createUserWithEmailAndPassword(auth,$("email").value,$("password").value).catch(e=>$("authMsg").textContent=e.message);$("emailSignIn").onclick=()=>signInWithEmailAndPassword(auth,$("email").value,$("password").value).catch(e=>$("authMsg").textContent=e.message);
$("saveProfile").onclick=async()=>{if(!$("displayName").value.trim())return;await setDoc(doc(db,"users",user.uid),{name:$("displayName").value.trim(),email:user.email,seasonPool:$("seasonPool").checked,role:"player",createdAt:serverTimestamp()});await loadProfile()};
$("savePicks").onclick=async()=>{await setDoc(doc(db,"weeks","week-1","entries",user.uid),{uid:user.uid,name:profile.name,picks,tiebreak:{clemson:Number($("clemsonScore").value),lsu:Number($("lsuScore").value)},updatedAt:serverTimestamp()},{merge:true});$("saveMsg").textContent="Picks saved to Firebase.";renderMy()};
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
onAuthStateChanged(auth,async u=>{user=u;$("loginCard").hidden=!!u;if(u){$("authBox").innerHTML=`<button id="logout">${u.email} · Sign out</button>`;$("logout").onclick=()=>signOut(auth);await loadProfile()}else{$("authBox").innerHTML="";$("profileCard").hidden=true;$("appArea").hidden=true}});